### ISSUE TITLE
Error with plist playlist

### ISSUE THREAD

**Issue by el07694** [wenerme/Lizzy#5]
```
root@chris-Inspiron-3847:~/eclipse-workspace/Lizzy-1.1.1# sh Transcode.sh -t rss samples/test02.plist
*** Lizzy Transcode v1.1.1
*** Copyright (c) 2008-2009, Christophe Delory
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
	at christophedelory.playlist.rmp.RmpProvider.readFrom(RmpProvider.java:101)
	at christophedelory.playlist.SpecificPlaylistFactory.readFrom(SpecificPlaylistFactory.java:132)
	at christophedelory.lizzy.Transcode.run(Transcode.java:291)
	at christophedelory.lizzy.Transcode.main(Transcode.java:122)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 4 more
```

**Comment by el07694** [comment]
Error from ubuntu.

**Comment by el07694** [comment]
That's because & symbol must be escaped.
